# Shell
brew "powerlevel10k"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Version managers
brew "fnm"
brew "chezmoi"

# Git
brew "git"
brew "gh"

# Utilities
brew "wget"

# Dev tools
cask "visual-studio-code"
cask "docker"
cask "postman"
cask "fork"            # Git GUI
cask "tableplus"
cask "dbeaver-community"

# Productivity
cask "google-chrome"
cask "discord"

# System utilities
cask "scroll-reverser" # natural scrolling
cask "jordanbaird-ice" # menu bar manager
